name: sync-fork
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  sync:
    # Only set the topic `has-issrc-build-env-sync-token` if the secret is available
    if: contains(github.event.repository.topics, 'has-issrc-build-env-sync-token')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: gh repo sync $REPOSITORY -b $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.ISSRC_BUILD_ENV_SYNC_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
      - run: |
          PR_NUMBER=$(gh pr list --repo "$REPOSITORY" --state open --base "$PR_BASE" --json number,headRefName,headRepositoryOwner --jq ".[] | select(.headRefName == \"$BRANCH_NAME\") | .number" | head -n 1)
          echo "PR_NUMBER=$PR_NUMBER"
          if [ -n "$PR_NUMBER" ] && [ "$PR_NUMBER" != "null" ]; then
            # see https://github.com/cli/cli/issues/10598#issuecomment-2893526162
            gh alias set save-me-copilot 'api --method POST /repos/$1/pulls/$2/requested_reviewers -f "reviewers[]=$COPILOT_LOGIN"'
            gh save-me-copilot "$REPOSITORY" "$PR_NUMBER"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.ISSRC_BUILD_ENV_SYNC_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
          PR_BASE: copilot-review
          COPILOT_LOGIN: copilot-pull-request-reviewer[bot]
