name: sync-fork
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  sync:
    # Only set the topic `has-issrc-build-env-sync-token` if the secret is available
    if: contains(github.event.repository.topics, 'has-issrc-build-env-sync-token')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: gh repo sync $REPOSITORY -b $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.ISSRC_BUILD_ENV_SYNC_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
      - run: |
          PR_NUMBER=$(gh pr list --repo "$REPOSITORY" --state open --base "$PR_BASE" --head "$REPOSITORY_OWNER:$BRANCH_NAME" --limit 1 --json number --jq '.[0].number')
          echo "PR_NUMBER=$PR_NUMBER"
          if [ -n "$PR_NUMBER" ] && [ "$PR_NUMBER" != "null" ]; then
            gh api \
              repos/$REPOSITORY/pulls/$PR_NUMBER/requested_reviewers \
              --method POST \
              -f reviewers[]="$COPILOT_LOGIN"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.ISSRC_BUILD_ENV_SYNC_TOKEN }}
          GH_TOKEN: ${{ secrets.ISSRC_BUILD_ENV_SYNC_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}
          BRANCH_NAME: ${{ github.ref_name }}
          PR_BASE: copilot-review
          COPILOT_LOGIN: github-copilot
